# MCXboxBroadcast Standalone Configuration
connection:
  host: "NehemiahGames.aternos.me"
  port: 17876

bot:
  # This shows as the World Owner (Top Text)
  shown_name: "NehemiahGames"
  # This shows as the World Name (Bottom Text) in Blue
  description: "§1Beta Games"

settings:
  language: "en-US"
  auto-update: true
